### ISSUE TITLE
Meta: We should make it easier to pick up single issues for people who weren't at Zurihac

### ISSUE THREAD

**Issue by PPKFS** [haskell/error-messages#185]
We have that very big list of tasks, but this isn't very clear. 

We can convert these to individually tracked issues - e.g. #183 - which means there does not need to be someone with write access to continually update the list.

We could also get some kind of automatic triaging bot to then assign these labels (project:error-index perhaps?). We could then have further human triaging - linking to relevant tests in GHC, tagging easy issues as low hanging fruit (e.g. "parse error: construct where it should not be").

I've done something similar at work (I proposed a new triage system, I got the go ahead, and I implemented it).

My concrete proposal:

- [x] Link every individual point to an issue
- [x] Mark up those of which are easy to pickup
- [x] Make it clear how people can document, help, etc. when not necessarily having the time to commit an entire code.

**Comment by david-christiansen** [comment]
You've done number 2 above now, right?

**Comment by PPKFS** [comment]
So on one hand yes, I think I have done all 3 of the above.

On the other, I think that 2) could use a second once-over with a fresh pair of eyes (maybe I misread an error, maybe I missed a bunch) and 3) is a continuous thing. 

But yes, it's done by me to a degree :)
